platform :ios, '8.0'

target ‘todoListAuth’ do
    source 'https://github.com/CocoaPods/Specs.git'
    pod 'React', :subspecs => ['Core', 'RCTImage', 'RCTNetwork', 'RCTText', 'RCTWebSocket'], :path => '../node_modules/react-native'
    pod 'react-native-camera', path: '../node_modules/react-native-camera'
end